trade-tariff/common/iam.tf

https://transformuk.atlassian.net/browse/HOTT-2775
https://github.com/trade-tariff/trade-tariff-backend/pull/1109
- This is required to validate status of the new version upgrade and avoid applying associations before the previous one is available
- Because AWS haven't done basic queueing on their events

HOTT-2775: Adds list-package-for-domain permission to ci user

---

aws/acm/terraform.tf
aws/waf/main.tf

https://transformuk.atlassian.net/browse/HOTT-2885
- Cloudfront resources always have to be in the us-east-1 region

HOTT-2885: Configure WAF provider region

---

aws/cloudfront/README.md
aws/cloudfront/main.tf
aws/cloudfront/terraform.tf
aws/cloudfront/variables.tf

- Removed the strict version check on the CloudFront module.
- Removed unused variable declarations.
- In order to be able to use the CloudFront module with newer AWS provider versions, this needs to be less strict.
- TFLint was complaining about unused variables.
- I need a new version of this module :)

BAU: Loosen CF module provider version

---

github/repos/README.md
github/repos/main.tf
github/repos/variables.tf
github/repos/versions.tf

- Removed the `ignore_changes` argument where a value of `etag` was specified.
- Added types for variables where this was missing.
- Terraform throws a warning with this; `etag` is decided by the provider alone and there can be no configured value to compare with.

BAU: Suppress etag warning by removing ignore_changes element

---

aws/ecs-service/main.tf

- Updated all `true` values to strings: `"true"`.
- When go attempts to unmarshal these values into strings it fails, so we need to make sure we're always providing strings.

BAU: Fix values being provided as bools

---

aws/ecs-service/README.md
aws/ecs-service/iam.tf
aws/ecs-service/variables.tf

_I have added/removed/altered:_
- Removed `managed_policy_arns` from the IAM roles we create in the ECS service module
- Replaced the required attachments for ECS with `aws_iam_role_policy_attachment` resources
- Added extra `aws_iam_role_policy_attachment` resources so the module can take in additional policy ARNs
_I am doing this because:_
Currently in the ECS service module, we're creating the service roles and provisioning them with [`managed_policy_arns`][0], but when we want to attach additional policy down the line to allow the service roles access to SecretsManager Secrets/ SSM parameters and KMS keys, using `aws_iam_role_policy_attachment` means we fall foul of [this application note][1]:
> **Warning**
> For a given role, this resource is incompatible with using the [aws_iam_role …

BAU: Allow extra IAM policy ARNs to be added

---

aws/ecs-service/README.md
aws/ecs-service/main.tf
aws/ecs-service/variables.tf

- Set the ECS service timeout through a variable.
- We can't set deregistration delay with an Application Load Balancer target group, so there's no way of terminating draining connections faster.
- We may wish to increase this per-environment later if we have a lot of tasks.

BAU: Set timeouts via variable

---

aws/opensearch/README.md
aws/opensearch/main.tf
aws/opensearch/outputs.tf
aws/opensearch/variables.tf
aws/opensearch/versions.tf

[HOTT-3551](https://transformuk.atlassian.net/browse/HOTT-3551)
_I have added/removed/altered:_
- Added output for the OpenSearch domain ARN.
- Bumped the ACM module version inside this module as it was out of date.
- Removed an unused variable.
_I am doing this because:_
- We need the ARN of the OpenSearch domain so that we can use it where the module is called to create specific policies.

HOTT-3551: Expose OpenSearch Domain ARN

---

aws/ecs-service/README.md
aws/ecs-service/iam.tf
aws/ecs-service/variables.tf

_I have added/removed/altered:_
- Changed the additional policy attachment resources to use `count` instead of `for_each`.
- Updated the variable defaults inline with this change.
_I am doing this because:_
Using `for_each` here leads to a common pitfall, and a plan-time error:
> The “for_each” value depends on resource attributes that cannot be
> determined until apply, so Terraform cannot predict how many instances
> will be created.
What we want to do instead is use `count`, which will allow us to use inputs that are not known until apply time.

BAU: Use count for additional policy attachments

---

aws/ecs-service/README.md
aws/ecs-service/locals.tf
aws/ecs-service/main.tf
aws/ecs-service/variables.tf

This PR forms part of [HOTT-3673](https://transformuk.atlassian.net/browse/HOTT-3673).
_I have added/removed/altered:_
- Added support for Service Discovery, allowing a Service Discovery Service to be created.
_I am doing this because:_
- Currently, the module doesn't support service discovery and assumes that the service will have a target group attached.

HOTT-3673: Add Service Discovery Support

---

aws/cloudfront/README.md
aws/cloudfront/main.tf
aws/cloudfront/variables.tf

- Added configurable `CNAME` or `A` record selection for CloudFront module.
- Per RFC 1912 section 2.4:
> A CNAME record is not allowed to coexist with any other data.
- We need to use an `A` record for the origin instead of a `CNAME` as we want it at the apex.

BAU: Allow optional CNAME or A record

---

aws/ecs-service/README.md
aws/ecs-service/main.tf
aws/ecs-service/variables.tf

- Create a boolean to enable ECS Exec on the task.
- It's useful for debugging in development.

BAU: Allow Enable ECS Exec

---

aws/cloudfront/README.md
aws/cloudfront/outputs.tf

I have:
- Added outputs for the CloudFront module for consumption in Route 53 DNS records.
- We require some A records to the CDN.

BAU: Output CloudFront Domain Name and Zone ID

---

aws/waf/README.md
aws/waf/main.tf
aws/waf/versions.tf

- Removed `statement.rule_group_reference_statement.excluded_rule` as this no longer exists.
- Added `statement.rule_group_reference_statement.rule_action_override`.
- We need to upgrade to the AWS v5 provider and this module is expecting v4.

BAU: Upgrade WAF module to support AWS v5 provider

---

aws/ecs-service/README.md
aws/ecs-service/main.tf
aws/ecs-service/variables.tf

- Added `command` support to the container definition in the ECS Service module.
- We need to be able to override the Dockerfile's `CMD` instruction when we deploy the "worker mode" backend services. To do this, we need to provide `command` in the container definition.

BAU: Support Command Override

---

aws/ecs-service/README.md
aws/ecs-service/main.tf
aws/ecs-service/variables.tf

I have:
- Made the `load_balancer` block in the ECS service module a `dynamic`.
- Gave `target_group_arn` variable a default of `null`.
- Added support for overriding `entrypoint` in the container definition.
- We dont want to have a load balancer configuration for the worker services, as they don't need health checking or traditional load balancing in this case.
- We need to be able to override `entrypoint` for the worker services, so that we can pass in a different command to them.

BAU: ECS Service improvements for backend workers

---

aws/ecs-service/README.md
aws/ecs-service/main.tf
aws/ecs-service/variables.tf

[HOTT-3876](https://transformuk.atlassian.net/browse/HOTT-3876)
- Added CodeDeploy app, deployment group resources
- Added variables to enable blue-green
- We need to add blue-green to our services so that we don't have downtime when deploying. The easiest way to achieve that within the constraints of AWS and ECS is to use [CodeDeploy](https://docs.aws.amazon.com/AmazonECS/latest/userguide/deployment-type-bluegreen.html)
- I have chosen to start with `CodeDeployDefault.ECSAllAtOnce`:
> Shifts all traﬃc to the updated Amazon ECS container at once.
But we may wish to discuss whether we want one of the other options here. Many of them take a lot longer to achieve full traffic switching. We may want to configure this for production.

HOTT-3876: Add Blue-Green Deployment Group

---

aws/ecs-service/README.md
aws/ecs-service/variables.tf

- Set a default for `deployment_configuration` of `null`.
- Without a default, this argument is required - but it is only used when `enable_blue_green` is `true` which may not always be the case.

BAU: Set a default for deployment_configuration

---

aws/ecs-service/README.md
aws/ecs-service/locals.tf
aws/ecs-service/main.tf
aws/ecs-service/variables.tf

[HOTT-2789](https://transformuk.atlassian.net/browse/HOTT-2789)
- Added support for running an init container which has individual overrides for entrypoint and command.
- The backend service has a lot of complexity that we need to rationalise as part of the migration to AWS. Namely, I would like to move the database migration steps out of a piece of arbitrary CircleCi compute and deal with it using an init container.
- This is common in [Kubernetes](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/), but as we are using ECS we need to adapt this approach by using the `dependsOn` property available to ECS container definitions.
- With this approach, we can create a set of init containers that run the database …

HOTT-2789: Support an Init Container

---

aws/cloudwatch_log_exporter/README.md
aws/cloudwatch_log_exporter/lambda/cloudwatch-to-s3.py
aws/cloudwatch_log_exporter/main.tf
aws/cloudwatch_log_exporter/terraform.tf
aws/cloudwatch_log_exporter/variables.tf
aws/cloudwatch_log_exporter/versions.tf

HOTT-4088
-  In order to export cloudwatch logs to logging s3 buckets

HOTT-4088 - added terraform module for cloudwatch log group export to s3

---

aws/aws-notify-slack/.pre-commit-config.yaml
aws/aws-notify-slack/README.md
aws/aws-notify-slack/functions/.flake8
aws/aws-notify-slack/functions/.pyproject.toml
aws/aws-notify-slack/functions/Pipfile
aws/aws-notify-slack/functions/README.md
aws/aws-notify-slack/functions/events/cloudwatch_alarm.json
aws/aws-notify-slack/functions/events/guardduty_finding_high.json
aws/aws-notify-slack/functions/events/guardduty_finding_low.json
aws/aws-notify-slack/functions/events/guardduty_finding_medium.json
aws/aws-notify-slack/functions/integration_test.py
aws/aws-notify-slack/functions/messages/cloudwatch_alarm.json
aws/aws-notify-slack/functions/messages/dms_notification.json
aws/aws-notify-slack/functions/messages/glue_notification.json
aws/aws-notify-slack/functions/messages/guardduty_finding.json
aws/aws-notify-slack/functions/messages/text_message.json
aws/aws-notify-slack/functions/mylambda.py
aws/aws-notify-slack/functions/notify_slack.py
aws/aws-notify-slack/functions/notify_slack_test.py
aws/aws-notify-slack/functions/snapshots/snap_notify_slack_test.py
aws/aws-notify-slack/iam.tf
aws/aws-notify-slack/main.tf
aws/aws-notify-slack/outputs.tf
aws/aws-notify-slack/variables.tf
aws/aws-notify-slack/versions.tf

HOTT-4081
- Added terraform module to send aws cloudwatch alarm alerts to slack
- To send slack alerts on triggered cloudwatch alarms

HOTT-4081 - added terraform module to send aws cloudwatch alarm alerts to slack

---

aws/cloudfront/README.md
aws/cloudfront/main.tf
aws/ecs-service/README.md
aws/ssm/example/README.md
aws/waf/README.md

https://transformuk.atlassian.net/browse/HOTT-4358
- You can't access a bucket as an OAI without permissions

HOTT-4358: Enable Origin Access Identities on s3 origins

---

aws/cloudfront/main.tf

- Added support for a response headers policy in CloudFront module
- We need to associate a response headers policy with our CloudFront distributions

BAU: Support Response Headers Policy (CloudFront)

---

aws/ecs-service/locals.tf

[HOTT-4852](https://transformuk.atlassian.net/browse/HOTT-4852)
- Changed init containers to be non-essential.
- Updated main service container definition to require an exit code of `0` on the init container before starting.
- Our use of this init container is to run database migrations. If the migration is not successful (i.e. the migration fails) it should fail the deployment.

HOTT-4852: Make init containers require exit code of 0

---

aws/cognito/README.md
aws/ecs-service/README.md
aws/waf/README.md
github/repos/README.md
github/repos/variables.tf

BAU
- These don't create merge commits which are needed to highlight merged pull requests for our release process.
- I misunderstood and approved this change, here https://github.com/trade-tariff/trade-tariff-platform-terraform-modules/pull/9/files
- I'm leaving this option since its technically possible in some repos for this not to affect releases

BAU: Disable squash commits

---

aws/cognito/main.tf
aws/cognito/variables.tf

BAU
- The inverted logic is confusing to the clients of the cognito module
- The default value of true is what's actually live in all environments today (we can manually change these separately)

BAU: Fixes broken registration logic

---

aws/waf/main.tf

HMRC-635
Currently we use a 5 minute window for WAF rate sampling.  This PR reduces that to a minute to improve reaction speeds

HMRC-635 Reduce WAF sample window

---

aws/cognito/README.md
aws/cognito/main.tf

HOTT-<TODO>
- Added a `lifecycle` block to prevent Terraform from overwriting the `invite_message_template` in the `aws_cognito_user_pool` resource.
- This change ensures that custom invitation messages set manually are not overwritten by Terraform during future runs.
- This change could bring down our developer flows and cause disruption
- The core application uses these resources

Configure invitation message

---

aws/ecs-service/README.md
aws/ecs-service/main.tf
aws/ecs-service/variables.tf

https://transformuk.atlassian.net/browse/HMRC-798
- I want to make adjustments to this module to support arbitrary scheduled tasks and I discovered this change was broken when updating this module recently

Revert "Merge pull request #68 from trade-tariff/hmrc-936-availability-zone-rebalancing"

---

.github/workflows/terraform.yml
aws/ecs-service/README.md
aws/ecs-service/data.tf
aws/ecs-service/locals.tf
aws/ecs-service/main.tf

[HMRC-798](https://transformuk.atlassian.net/browse/HMRC-798)
- Essentially, we do not want autoscaling policies/actions to kick in when we're running a job.
We've noticed that when running a long running job this will stop our
container mid-job which is undesirable/leaving development in a broken
state

HMRC-798: Adds handling for job autoscaling

---

aws/ecs-service/main.tf

BAU
- The RunningTaskCount metric is available under ECS/ContainerInsights, not AWS/ECS.
- This change could bring down our developer flows and cause disruption
- The core application uses these resources

Fix cloudwatch service count alert
